import type { Metadata } from 'next';

import './globals.css';

export const metadata: Metadata = {
  title: 'admin',
  description: 'Generated by byuckchon-frontend-cli',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <head>
        <meta charSet="utf-8" />
      </head>
      <body>{children}</body>
    </html>
  );
}
